### ISSUE TITLE
Error importing Individual from NiaPy

### ISSUE THREAD

**Issue by jwainer** [karakatic/EvoPreprocess#3]
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) 
    [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

    >>> import NiaPy
    >>> NiaPy.__version__
    '1.0.2'

    >>> from EvoPreprocess.data_sampling import EvoSampling
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/miniconda3/envs/nia/lib/python3.6/site-packages/EvoPreprocess/__init__.py", line 15, in <module>
        from . import data_sampling
      File "/opt/miniconda3/envs/nia/lib/python3.6/site-packages/EvoPreprocess/data_sampling/__init__.py", line 6, in <module>
        from .EvoSampling import EvoSampling
      File "/opt/miniconda3/envs/nia/lib/python3.6/site-packages/EvoPreprocess/data_sampling/EvoSampling.py", line 15, in 
    <module>
        from NiaPy.algorithms import Individual
    ImportError: cannot import name 'Individual'
    >>>

**Comment by jwainer** [comment]
This is a non-issue. The problem is that `pip NiaPy` installs the 1.0.2 version of NiaPy which is **NOT** the version required by EvoPreprocess (setup.py asks for 'NiaPy>=2.0.0rc5') NiaPy must be installed via `git + python setup`
